name: Deploy React App to CloudFront

on:
  workflow_dispatch:
  
permissions:
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup environment variables
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> .env

      - name: Build React app
        run: npm run build
        env:
          CI: ""

      - name: Upload frontend build file to artifact
        uses: actions/upload-artifact@v4
        with:
          name: FrontendApplication
          path: frontend/build

  deploy:
    needs: build-and-deploy
    runs-on: self-hosted
    env:
      CLOUD_FRONT_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID}}
      S3_NAME: ${{ secrets.AWS_S3_NAME }}
    steps:
      # - name: Remove previous version app
      #   working-directory: frontend/
      #   run: rm -rf dist
  
      - name: Download build file from artifact
        uses: actions/download-artifact@v4
        with:
          name: FrontendApplication
          path: frontend/build
  
      - name: Deploy DEV frontend
        working-directory: frontend/
        run: |
          aws s3 sync build/ s3://S3_NAME --delete
          aws cloudfront create-invalidation --distribution-id CLOUD_FRONT_DISTRIBUTION_ID --paths "/*"
